project_id = "lbqvsvlckglqjdpoobpo"

[functions.growth-assistant]
verify_jwt = true

[functions.chat-gemini]
verify_jwt = false

[functions.generate-share-link]
verify_jwt = true

[functions.analyze-disease]
verify_jwt = true

[functions.google-calendar]
verify_jwt = true